locale: "en-US"
title: KodeGuide # Title of your site
url: "http://kabayomi.info" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: "UA-96670172-1"

# Default description in social shares for the jekyll-seo-tag gem
description:  # this means to ignore newlines until "baseurl:"
  For the love of engineering and tech and all the other things that comes in-between

# Author details for the jekyll-seo-tag gem
author:
  name: Abayomi Koyejo
  email: kabayomi007@gmail.com
  twitter: kabayomi007 # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
